version: '3.0'

WORKDIR /home/vagrant

RUN mkdir trf
RUN git init
RUN g

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: '!Abc123'
       MYSQL_DATABASE: 'trf'
       MYSQL_USER: 'trf'
       MYSQL_PASSWORD: '4linux'
     volumes:
     - mysql_data:/var/lib/mysql

   app:
     image: trf-php 
     ports:
     - "8080:8080"
     restart: always
     environment:
       DB_HOST: 'mysql'
       DB_PORT: '3306'
       DB_USER: 'trf'
       DB_PASS: '4linux'
       DB_NAME: 'trf'
     ports:
     - '8080:8080'  
volumes:
  mysql_data: {}
